### ISSUE TITLE
Kinvey.Error doesn't conform to LocalizedError

### ISSUE THREAD

**Issue by sharplet** [Kinvey/ios-library#173]
### Description

`Kinvey.Error.localizedDescription` gives an unhelpful error message:

![simulator screen shot jan 26 2017 10 13 07 am](https://cloud.githubusercontent.com/assets/147686/22336908/b91dbdde-e3b1-11e6-877c-d8a3f9e1b3c7.png)

This issue would be fixed by adding `LocalizedError` conformance. See https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md#proposed-solution.

### Steps to reproduce 

Trigger a `Kinvey.Error`, for example by logging in with the wrong password.

### Kinvey SDK Version

Using Kinvey from `develop`.

### Tool Versions (XCode / Swift / iOS / Device)

n/a

**Comment by heyzooi** [comment]
@sharplet thanks again for your contributions! Great suggestion!
We just pushed a new PR for that https://github.com/Kinvey/ios-library/pull/174
Should be merged soon and will probably be in the next release.
